ASP_Shop/ASP_Shop/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ASP_Shop.Data;
using ASP_Shop.Models;
using ASP_Shop.Services;

namespace ASP_Shop.Controllers;
[Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
        if (obj.Name == obj.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
        }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["succes"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
        if (obj.Name == obj.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
        }
        if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["succes"] = "Category edited successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);


            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);

        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            TempData["succes"] = "Category deleted successfully";
            return RedirectToAction("Index");

        }
    }

ASP_Shop/ASP_Shop/Areas/Admin/Controllers/ProducentController.cs
using Microsoft.AspNetCore.Mvc;
using ASP_Shop.Data;
using ASP_Shop.Models;
using ASP_Shop.Services;

namespace ASP_Shop.Controllers;
[Area("Admin")]
    public class ProducentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ProducentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Producent> objProducentList = _unitOfWork.Producent.GetAll();
            return View(objProducentList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Producent obj)
        {
        if (obj.Name == obj.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
        }
            if (ModelState.IsValid)
            {
                _unitOfWork.Producent.Add(obj);
                _unitOfWork.Save();
                TempData["succes"] = "Producent created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var producentFromDbFirst = _unitOfWork.Producent.GetFirstOrDefault(u => u.Id == id);

            if (producentFromDbFirst == null)
            {
                return NotFound();
            }

            return View(producentFromDbFirst);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Producent obj)
        {
        if (ModelState.IsValid)
            {
                _unitOfWork.Producent.Update(obj);
                _unitOfWork.Save();
                TempData["succes"] = "Producent edited successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var ProducentFromDbFirst = _unitOfWork.Producent.GetFirstOrDefault(u => u.Id == id);


            if (ProducentFromDbFirst == null)
            {
                return NotFound();
            }

            return View(ProducentFromDbFirst);

        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.Producent.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Producent.Remove(obj);
            _unitOfWork.Save();
            TempData["succes"] = "Producent deleted successfully";
            return RedirectToAction("Index");

        }
    }

ASP_Shop/ASP_Shop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using ASP_Shop.Data;
using ASP_Shop.Models;
using ASP_Shop.Services;

namespace ASP_Shop.Controllers;
[Area("Admin")]
public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    public ProductController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }
    public IActionResult Index()
    {
        IEnumerable<Product> objProductList = _unitOfWork.Product.GetAll();
        return View(objProductList);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Product obj)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Product.Add(obj);
            _unitOfWork.Save();
            TempData["succes"] = "Product created successfully";
            return RedirectToAction("Index");
        }
        return View(obj);

    }

    public IActionResult Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var productFromDbFirst = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);

        if (productFromDbFirst == null)
        {
            return NotFound();
        }

        return View(productFromDbFirst);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Product obj)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Product.Update(obj);
            _unitOfWork.Save();
            TempData["succes"] = "v edited successfully";
            return RedirectToAction("Index");
        }
        return View(obj);

    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        var productFromDbFirst = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);


        if (productFromDbFirst == null)
        {
            return NotFound();
        }

        return View(productFromDbFirst);

    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }
        _unitOfWork.Product.Remove(obj);
        _unitOfWork.Save();
        TempData["succes"] = "Product deleted successfully";
        return RedirectToAction("Index");

    }
}

ASP_Shop/ASP_Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_Shop</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
          <div class="dropdown-menu">
            <a class="dropdown-item"  asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
            <div class="dropdown-divider"></div>
             <a class="dropdown-item" asp-area="Admin" asp-controller="Producent" asp-action="Index">Producent</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">User</a>
          <div class="dropdown-menu">
            <a class="dropdown-item"  asp-controller="Home" asp-action="Index">Home</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted bg-dark" style="top:auto;">
        <div class="container">
            &copy; 2022 - ASP_Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP_Shop/ASP_Shop/Views/Shared/_Notification.cshtml
@if(TempData["succes"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type ="text/javascript">
        alert('@TempData["succes"]');
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type ="text/javascript">
        alert('@TempData["error"]');
    </script>
}